### ISSUE TITLE
Student's income out of range for integer

### ISSUE THREAD

**Issue by andrepestana-aot** [bcgov/SIMS#2214] opened 2023-08-22 16:05 UTC
Student application form allows a too large number that cannot be converted to integer in the worker:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjhuIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--487ebe88713afbad7650b5628022165773f6d40a/image.png)

## Logs from the workers:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0VvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--33e15fe66ba9e70f9b58725e1758a82910d8ca98/image.png)

## It doesn't cause an incident and stops the workflow:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2tvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b2e1279b537e62033379eeea44f5eef0b8dc9331/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1lvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5280b27378fabd122f1bc4ad24ea2085ab5a7fae/image.png)

***Acceptance Criteria***
- [ ] Test the workflow and check if it creates an incident in case that or something else wrong happens (maybe it is already creating an incident instead of stopping the workflow).
- [ ] Impose a maximum integer value of 100,000,000 for this income field.

**Comment by michesmith** [comment] 2024-01-09 21:54
@andrepestana-aot  does this ticket require SABC input? Can you please draft some acceptance criteria in advance of grooming?

**Comment by andrepestana-aot** [comment] 2024-01-09 22:55
> @andrepestana-aot does this ticket require SABC input? Can you please draft some acceptance criteria in advance of grooming?

That would be good to have some SABC input but even if we don't have any, we still can work on that validating with the max possible value. I added the ACs.

**Comment by michesmith** [comment] 2024-01-10 17:23
@HRAGANBC @CarlyCotton  could you please have a look and confirm requirement here +add draft acceptance criteria if a appropriate?. thank you

**Comment by CarlyCotton** [comment] 2024-01-10 17:33
@andrepestana-aot What is the limit the integer will support in this case? 2147483647?

**Comment by HRAGANBC** [comment] 2024-01-11 15:39
@CarlyCotton @andrepestana-aot Yes, 9 digits is fine. 100 million annual income is more than sufficient as a cap. I have added this into the ticket itself.

**Comment by ninosamson** [comment] 2024-02-01 19:18
Potential duplicate - confirm and close if #2688 resolves the bug.

**Comment by ninosamson** [comment] 2024-02-07 17:48
Confirmed duplicate of 2688.

**Closed** 2024-02-07 17:48 UTC
Labels: Bug, Student, Form.io, Camunda Workers
