### ISSUE TITLE
UX Institution Edits Program / Study Periods (after COE)

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#862] opened 2021-11-19 23:26 UTC
### Describe task

- Institution requests a program / offering change (when students are enrolled)
- Use reassessment analysis #759 to inform mockup solution
- Related UX ticket #882

### Acceptance Criteria
- [x] Institution - mockup requesting a program change, the following rules apply:
- Institutions can edit all fields if no students are in it (linked to the program)
- Institutions can only edit Name and Description if students are in it (linked to the program)
- [x] Institution - mockup requesting an offering change, the following rules apply:
- Institutions can edit all fields if no students are in it (linked to the offering)
- Institutions can only edit Name if students are in it (linked to the offering)
- If an institution needs to request change to offering details, they must request a change which leads to ministry users to accept/decline and reassess (bulk) 
- [x] Ministry - mockup approving study period change (yes/approve REASSESS / no/decline DO NOT REASSESS))

**Comment by hellolynn-dsib** [comment] 2022-02-10 18:03
Blocked waiting for business requirements/feedback

**Comment by hellolynn-dsib** [comment] 2022-02-14 21:06
Feedback sent. Suggest revisiting MVP options with PO.

**Comment by hellolynn-dsib** [comment] 2022-02-16 20:53
### Feedback

Hi Lynn,  

Following on the EPI team’s earlier feedback re: the importance of IPDT and SST involvement in the review of editing programs and study periods, I am sending the remaining feedback gathered from the EPI team and the Sector Advisor.
 
Figma Feedback 
•	Overall feedback/questions 
•	Would informational updates e.g. to program or study period name/description, CIP, etc. get pulled through to all areas where they're implicated (e.g. to applications)? 
o	If yes, to what extent e.g. to all active/current applications or are changes also retroactively applied to historical applications? 
o	Will there be a historical record in the system of past variations e.g. of  a program or study period that is subsequently changed?
•	General rule of thumb for program and study period level fields would be that anything which could impact/change assessment requires pending status for manual review
o	Flagging this as a review area for those working in the area of assessment/reassessment and CoE
•	Program level 
•	See question re: information updates under overall feedback/questions above -  potential impacts to whether changes in program name, description and CIP would require pending status
•	Note regarding CIP: When CDW data clean-ups are conducted and Institutional Research units update CIP codes, FAOs are not looped in – it was mentioned to the team that it would be important for FAOs to have oversight of the CIP codes assigned to programs in SIMS, and that if in a future state with more integration e.g. with CDW updates, something like a flag noting a difference between CDW data and what’s listed for the program in SIMS could alert the institution to a need for reviewing the CIP in SIMS
•	Regulatory body is currently under “auto-approve” and may require “pending” status for manual review 
•	In certain cases, program changes/shifts may be better managed by an institution creating a new program in the system and having students apply to that (e.g. changes that impact core program characteristics like program name, credential type and CIP could be better served by entering a new program and having incoming students apply to that new version)
•	Study period level 
•	See question re: information updates under overall feedback/questions above -  potential impacts to whether a change in study period name would require pending status
o	Study period name/description changes could impact student’s selection and whether they’re in the right study period with the correct costs (e.g. if study period entered incorrectly as a regular study period when it is in fact a WIL/co-op term)
•	Delivery confirmed as a change that would require pending status for manual review e.g. due to different transportation allowance for fully online vs. onsite and blended study periods 
•	Study dates confirmed as a change that requires pending status for manual review
•	Study breaks need to be added as a change that would require pending status for manual review as changes could impact the number of funded weeks in the study period

It was raised as part of this discussion that there are two main pieces to changing programs/study periods – approving the changes to be updated in SIMS, and approving the reassessment for students.

Hope that this feedback from the EPI side of editing programs/study periods is helpful – happy to discuss with you further if needed!

**Comment by hellolynn-dsib** [comment] 2022-03-10 17:35
To review in backlog with DEVS

**Closed** 2022-04-19 22:56 UTC
Labels: User Experience, Institution, Ministry
