### ISSUE TITLE
Ministry Trigger Scholastic Standing

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#3591] opened 2024-07-30 22:07 UTC
**User Story**
As a ministry user, I want to be able to trigger a scholastic standing event to take action on an application in the event an institution is not.

**Acceptance Criteria**
- [ ] Report a change but for Institution?
- [ ] What group/user level?

**Comment by CarlyCotton** [comment] 2024-07-30 23:13
Closing - this is a duplicate of #1798

**Closed** 2024-07-30 23:14 UTC
Labels: Ministry, Business
