### ISSUE TITLE
Report a Withdrawal Not Working

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2241] opened 2023-08-31 21:35 UTC
**Current Behaviour**
- Student with complete application is reported as withdrawn by institution --> error message generated and withdrawal cannot be reported
- Other scholastic events (UC, early completion) can be reported successfully without issue

E.g. Student Application -- see details in photo below

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVJjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c25d63aa8684fa90e250c92586183e8644a4aac7/image.png)

** Acceptance Criteria **
- [ ] Conduct analysis to confirm the root cause and resolve. Possibly related to ticket #2484 or a data issue
- [ ] Student with complete application is reported as withdrawn by institution without error

**Comment by sh16011993** [comment] 2024-01-03 18:21
The following program and offering were created to reproduce the bug:

Program Details: 
<img width="1915" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW1YQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ab380bae479f5fab398b17c5df9e1e242b8ff14/image.png" alt="image.png" />

Offering Details:
<img width="1507" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXVYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dee9300c2524b3f6efc94304a649f9693989c6fa/image.png" alt="image.png" />

The following application was submitted:

<img width="1505" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekNYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d70ee8d19afe9e7d5a9736e91c34c492373590e/image.png" alt="image.png" />

After selecting "Report a Change", and selecting scholastic standing type "Student Withdrew from program", the change was reported successfully without any errors.
<img width="1506" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejJYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d559b28838ea011fc78fa81a88172956baa46647/image.png" alt="image.png" />

**Comment by sh16011993** [comment] 2024-01-03 18:26
Closing this issue since the bug couldn't be replicated with the parameters from the attached screenshot.

**Closed** 2024-01-04 17:57 UTC
Labels: Bug
