### ISSUE TITLE
WAITING: NEED TO REPRODUCE: MSFAA Response files are being archived, but original file not being deleted. 

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#3916] opened 2024-11-08 19:11 UTC
**Describe the Bug**
The MSFA Response files are being processed and copied over to the archive folder successfully, but the original files are not being deleted.

**Expected Behaviour**
After the file is processed and a copy placed in the archive folder, the original file should be removed from the IN folder on the SFTP server.

**Actual Behaviour**
Currently, the job is archiving the file sucessfully, but leaving the original file in the IN folder.

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. When there is a new MSFA file to process, execute part-time-msfaa-process-response-integration job in Bull Dashboard
2. Once complete, navigate to the IN\Archive folder and you will see a copy of the file there with a datetime stamp appended to the file name.  This is evidence that the job reached the stage of archiving the file after processing.
3. Navigate up one level to the IN folder and you will see the original file still there.

**Comment by CarlyCotton** [comment] 2024-11-19 18:27
Closing - can't reproduce.

**Closed by CarlyCotton** 2024-11-19 18:27 UTC
Labels: Bug, Business
