### ISSUE TITLE
Expand Dates when Student can Cancel their Application

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2683] opened 2024-01-15 18:39 UTC
**User Story:**
As a student, I want to be able to cancel my application even after COE (but before disbursements) so that I can 

**Current Behaviour:**
- Student can cancel up until COE is complete, then they cannot cancel after that, nor can the Ministry or Schools. 

**Context:**
- Scholastic Standing eligible reporting dates is another potential way of handling these scenarios

Questions:
- What does it do to study dates? Remove altogether?
- What does it do to funding amounts? 
-

**Comment by ninosamson** [comment] 2024-01-31 18:17
Potential duplicate of 2230.

**Closed** 2024-01-31 18:18 UTC
Labels: Question, Student
