### ISSUE TITLE
Scholastic Standing Cloning Offering 

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#1824] opened 2023-03-21 20:07 UTC
@HRAGANBC Let's discuss this further to ensure this is actually how we want this implemented (See acceptance criteria)

When a scholastic standing is created by the Institution and a new assessment must be processed,  the current application associated offering is cloned and it potentially will have the `offering end date` and/or `offering costs` updated. Once the `offering end date` is updated, we must ensure that the data in the column `study_breaks` on the table `sims.education_programs_offerings` is reflecting the correct amount of `totalFundedWeeks`.

Sample from `study_breaks` columns.
```json
{
  "totalDays": 267,
  "studyBreaks": [],
  "totalFundedWeeks": 39,
  "fundedStudyPeriodDays": 267,
  "unfundedStudyPeriodDays": 0
}
```

From the assessment-gateway perspective the value from the `totalFundedWeeks` is loaded as `offeringWeeks` and it is the value used for all week-based-calculations until it is finally also persisted to the NOA, as shown below.

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/f3a66580-0b65-4bfd-93fe-880994082536)

Reference point in code where the offering clone is happening.
https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/apps/api/src/services/student-scholastic-standings/student-scholastic-standings.service.ts#L189

**Acceptance Criteria** 
- [x]  Ensure that the `study_breaks` column will be updated using the `EducationProgramOfferingService.getCalculatedStudyBreaksAndWeeks`
- [x]  If change in study end date overlaps/crosses any study breaks, handle as follows:
  - If new study end date =< break start date, ignore study break
  - If new study end date => break end date, include study break as is.
  - If break start date < new study end date < break end date, update break end date with new study end date
  - During an offering creation when the break period is less than 6 days, offering is not allowed to create, In Scholastic standing, we do the above 3 steps and ignore all the validations(even if the new study break period is less than 6 days, we don't care, we still clone the offering with above-mentioned logic)
- [x] E2E Test/Unit Tests

**Comment by ann-aot** [comment] 2023-11-02 21:03
Removed below qns. as they are not part of the ticket,
Review with the business if we should actually change the totalFundedWeeks. Are we clear about how the scholastic standings reassessments are calculated?
Confirm Is scholastic standing "pro-rate" impacting this? How is it calculated?

**Comment by JasonCTang** [comment] 2023-11-02 22:11
Question 1 seems to be covered by the current state of the ACs.  
Question 2 is unclear and nobody seems to know specifically what it is referring to.  The only thing I could think of that could even be pro-rated is the study costs, but business confirmed that we DO NOT adjust study costs automatically (we do in the one scenario where the instiuttion provides new study costs).  So I'm making the call to ignore question 2 and move on with the ticket.

**Comment by ann-aot** [comment] 2023-11-02 22:30
This ticket need more clarification on "when there is study break, which is after the new study end date (withdrawal date) or new study end date (withdrawal date)  is in between the any of the study break, when should we do", 2nd AC was created as a solution of this, we need to review and clarify it.

**Comment by HRAGANBC** [comment] 2023-11-08 17:43
Option 1: Acceptance Criteria above:
- adjust the offering breaks and dates to reflect the new end dates
- Do not adjust offering costs.

Option 2: 
- ???

**Comment by andrewsignori-aot** [comment] 2023-11-09 21:45
@HRAGANBC is there any pending question to be answered for this ticket?
I was under the impression that the ACs look good and we can go ahead with it.
Also, why are we talking about the offering costs? They are adjusted as needed when the offering is cloned. Do we need change anything about it?

**Comment by HRAGANBC** [comment] 2023-11-09 22:08
@andrewsignori-aot AC's are all good from my perspective as they reflect what you and I landed on yesterday. 

Re. the offering costs, are you referring to Ann's initial question and then Jason's response? If so, the bottom line is that yes, we want to pro-rate (i.e. re-assess) the student when their end date changes (because of scholastic standing), but the only variable change driving the for pro-rating is the weeks of study, not the offering costs. 

I.e. when a student withdraws half-way through their study period, they get re-assessed for ~half the funding because they are now in studies for half the number of weeks, but we should not adjust the offering costs during the re-assessment.

**Comment by andrewsignori-aot** [comment] 2023-11-09 23:48
@HRAGANBC for the below situation we are requesting offering costs from the institution and we are adjusting these costs in the cloned offering that will be used for the reassessment calculation. Is it something that should stop doing also?

![image](https://github.com/bcgov/SIMS/assets/61259237/792fa40d-1de9-4b5c-acdb-509559a0aceb)

**Comment by HRAGANBC** [comment] 2023-11-10 00:19
@andrewsignori-aot  Last time I checked, the ability for schools to report revised costs was ONLY for Early Completion, and not Withdraw or others. That's fine. If those are the 'revised costs' you're talking about, that's totally fine to use those new costs in the re-assessment calculation. 

What I was worried about is the cloning process _automatically_ trimming the cost figures proportionally based on the shorter end dates, which should NOT happen, but it sounds like that's not happening anyways so thats great. 

I think we are all good!

**Comment by andrewsignori-aot** [comment] 2023-11-10 00:43
Thanks for the clarifications @HRAGANBC. I had a feeling that the point was about withdrawal only 😉 
From the SIMS perspective, the Scholastic Standing form submission and the cloning offering it is "the same" shared process across all the types. I believe that we are good to do.

**Closed** 2023-12-06 17:42 UTC
Labels: Bug, Student
