### ISSUE TITLE
[NEED TO REPRODUCE] Earliest Date of Disbursement Not within Study Period

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3459] opened 2024-06-24 19:06 UTC
**User Story**
As a ministry user, we need to ensure the earliest date of disbursement is no earlier than the date of the assessment OR earlier than the study dates of the offering. 

**Acceptance Criteria**
- [ ] Ensure the earliest date of disbursement is no earlier than the study start date AND no earlier than the assessment date.

**Business Context**
Students cannot receive disbursement prior to their study start date.
With a Study date of Sep 1 2024 to May 1 2025 (PY 2024-2025) with an assessment date of May 31 2024, the earliest date of disbursement should be September 1, 2024.
<img width="1418" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0tKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb880fff0a0aed0f6d86e9ebaa4f354ba3fb0502/image.png" alt="image.png" />

**Comment by michesmith** [comment] 2024-07-26 18:59
Cant reproduce this bug- so closing if it resurfaces

**Closed by michesmith** 2024-07-26 18:59 UTC
Labels: Bug, Student, Business
