### ISSUE TITLE
Analysis - Ignore Restrictions 

### ISSUE THREAD

**Issue by ninosamson** [bcgov/SIMS#3662] opened 2024-08-27 23:52 UTC
Note: Needs an epic to link all tickets @michesmith 

**Acceptance criteria**
- [x] Research ticket for #1862 and #1815
- [x] Add technical technicals to tickets.
- [ ] Create more tickets if needed.

NOTE: There's also #3028 and #3044

**Comment by andrewsignori-aot** [comment] 2024-08-28 18:13
## Analysis Assumptions
- Restrictions can be ignored even if not associated with the student yet, which means the Ministry can select any restrictions from the restrictions lists to be ignored.
- Restrictions ignored will be associated with the application ID, which means that editing an application will remove all ignored restrictions associated with that application number since a new application record with a new application ID is created.

**Comment by andrewsignori-aot** [comment] 2024-08-28 18:52
@Joshua-Lakusta a restriction bypass should also be part of the logic that prevents the student from accepting an assessment?
If a restriction currently preventing the student from accepting the assessment is bypassed, should the student be able to accept the assessment?

**Comment by andrewsignori-aot** [comment] 2024-08-28 19:14
@Joshua-Lakusta a bypassed restriction still be listed in the application tracker cards?
For instance, if the student has only one restriction blocking the disbursement and this restriction is ignored, should we still display the below message:
"You have a restriction on your account making you ineligible to receive funding. Please contact StudentAid BC if you still require assistance in identifying the cause of this issue and help resolving the issue."
My advice would be "do not show the message".

**Comment by andrewsignori-aot** [comment] 2024-08-28 19:24
@Joshua-Lakusta currently we have the below possible actions associated with a restriction.
- No effect;
- Stop full time BC funding (created automatically during disbursement);
- Stop part time apply;
- Stop full time apply;
- Stop part time disbursement;
- Stop full time disbursement.

Should we assume the restrictions bypass will be applied only for  `Stop part time disbursement` or `Stop full time disbursement`?
Is there any plan for `Stop full time BC funding`?

**Comment by Joshua-Lakusta** [comment] 2024-08-28 21:52
@Joshua-Lakusta a bypassed restriction should also be part of the logic that prevents the student from accepting an assessment?
If a restriction currently preventing the student from accepting the assessment is bypassed, should the student be able to accept the assessment?
My advice would be "allow the student to accept the assessment".
Yes I agree they should be able to accept assessment

@Joshua-Lakusta a bypassed restriction still be listed in the application tracker cards?
For instance, if the student has only one restriction blocking the disbursement and this restriction is ignored, should we still display the below message:
"You have a restriction on your account making you ineligible to receive funding. Please contact StudentAid BC if you still require assistance in identifying the cause of this issue and help resolving the issue."
My advice would be "do not show the message".
I agree we should not show the message.

@Joshua-Lakusta currently we have the below possible actions associated with a restriction.

No effect;
Stop full time BC funding (created automatically during disbursement);
Stop part time apply;
Stop full time apply;
Stop part time disbursement;
Stop full time disbursement.
Should we assume the restrictions bypass will be applied only for Stop part time disbursement or Stop full time disbursement?
Is there any plan for Stop full time BC funding?

As this is being handled as a manual ministry intervention we should allow them to bypass all restriction types that interfere with the assessment or disbursement. Stop full time BC funding is actually one that we specifically want this functionality for. If the restriction is bypassed we will need it to reassess. There is going to be further analysis around that one however, so we can postpone the issue of automatic reassessment of this one for the future.. At least allow it to be ignorable and if we need to reassess then we can manually force reassessment with the current manual reassess functionality we have now.

**Comment by andrewsignori-aot** [comment] 2024-08-28 23:27
@Joshua-Lakusta thanks for the reply all is clear but `Stop full time BC funding`.

There are two scanrios for the `Stop full time BC funding` during the disbursement.

### Scenario A
a) The student does not have the `Stop full time BC funding` associated yet, and
b) The student will reach the maximum, reducing his awards and creating the `Stop full time BC funding` to stop future BC funding awards.

### Scenario B
a) The student already has a `Stop full time BC funding` associated.
b) BC awards will be disbursed as $0.

### Question
When the restriction is bypassed, should we completely ignore the verification of the `Stop full time BC funding`?
Which means, 
- for `Scenario A` the restriction will never be created if the bypass is added ahead of time;
- for `Scenario B` the BC awards will be disbursed with total amounts.

**Comment by andrewsignori-aot** [comment] 2024-08-29 00:27
@Joshua-Lakusta I adjusted the "View Modal" as below trying to follow the existing ones from the restrictions.
It is close to the original layout but has some cleanups.

<img width="676" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBektYQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb0d4a29e32386e80d534cb25e604130eb50dba0/image.png" alt="image.png" />

**Comment by Joshua-Lakusta** [comment] 2024-08-29 17:11
@andrewsignori-aot added my answer into your comment on the two scenarios for Stop Full Time BC Funding. 

Look at the edit to the View Modal and it looks good overall.

**Comment by andrewsignori-aot** [comment] 2024-08-29 19:30
@Joshua-Lakusta based on the latest replies follow the questions.

Related to "The resolve restriction should only be useable when the restriction currently exists.".
Question 1: should we allow the Ministry to select only active restrictions in the student account?
Question 2: for the `Stop full time BC funding`, we should first allow the restriction to be created (and the award to be reduced) to then allow the restriction to be bypassed and the awards disbursed with their total amounts?

**Comment by andrewsignori-aot** [comment] 2024-08-29 23:57
@Joshua-Lakusta if a currently active student restriction is bypassed and later this restriction (federal or provincial) is marked as resolved, should we deactivate the bypass, or should we maybe display it in the list if the limitation is no longer active?

**Comment by andrewsignori-aot** [comment] 2024-08-30 16:56
> @Joshua-Lakusta if a currently active student restriction is bypassed and later this restriction (federal or provincial) is marked as resolved, should we deactivate the bypass, or should we maybe display it in the list if the restriction is no longer active? My recommendation would be to "display it in the list if the restriction is no longer active", for simplicity.
> 
> Josh- For me if the restriction is resolved it should no longer need to be bypassed as its not there. The history of the by pass should show etc so for me I think it should show that it was bypassed but that it no longer is just in case the restriction is added back on it needs to be clear that it needs to be "re bypassed".

@Joshua-Lakusta the scanrio is the below.
a) The restriction is active in the student account.
b) The active restriction is bypassed and is now on the list of bypassed restrictions.
c) The restriction is resolved in the student account, either manually or because it was a federal automatically resolved.

In the above scenario, the history of bypassed restrictions will still display the no longer active student restriction in the history which can be misleading to the user.

My recommendation would be to include the restriction status in the history to make it clear to the user.

**Closed** 2024-09-04 16:34 UTC

**Comment by michesmith** [comment] 2024-09-20 18:49
Moved this Note from Inside the ticket to comments  ": Needs an epic to link all tickets @michesmith. "  @ninosamson  The epics are 2.2.3 Student View Restrictions and 4.5.6 Ministry Mange Student Restrictions and are now tagged
